Repository UCLALibrary/californica, pull requests merged in 2018-08, with the labels that each got.

#43 Add a default admin user
  Capfile
  Gemfile
  Gemfile.lock
  config/deploy.rb
  db/seeds.rb
Labels: review

#52 Ensure derivatives persist between deploys
  config/initializers/hyrax.rb
Labels: review

#56 Add Genre
  app/models/work.rb
  spec/models/work_spec.rb
Labels: review

#57 Add extent to work model
  app/models/work.rb
  spec/models/work_spec.rb
Labels: review

#58 Add extent to importer
  app/ingest/mods_mapper.rb
  spec/ingest/mods_mapper_spec.rb
  spec/ingest/mods_xml_parser_spec.rb
Labels: in progress

#60 Add genre to ingest
  app/ingest/mods_mapper.rb
  spec/ingest/mods_mapper_spec.rb
  spec/ingest/mods_xml_parser_spec.rb
Labels: review

#61 Parameterize fedora and solr dev configs
  config/fedora.yml
  config/solr.yml
Labels: enhancement, review

#79 Add CSV metadata fixture
  spec/fixtures/example.csv
Labels: review

#80 Implement a CSV importer
  .rubocop.yml
  app/importers/californica_csv_parser.rb
  app/importers/californica_mapper.rb
  lib/tasks/ingest.rake
  spec/importers/californica_csv_parser_spec.rb
  spec/importers/californica_mapper_spec.rb
Labels: review

#81 Update dependencies
  Gemfile.lock
Labels: review

#82 Use SOLR_URL for Blacklight and Solr config
  .env.sample
  config/blacklight.yml
  config/solr.yml
Labels: review

#85 Add Fedora configuration to `dotenv`
  .env.sample
  config/fedora.yml
Labels: review

#84 Add deploy file for californica-test server
  config/deploy/californica-test.rb
Labels: review

#88 Simplify configs
  .env.sample
  config/blacklight.yml
  config/fedora.yml
  config/solr.yml
Labels: review

#90 Prepare configuration for UCLA deployment
  .env.sample
  .travis.yml
  Gemfile
  Gemfile.lock
  README.md
  config/cable.yml
  config/database.yml
  config/deploy.rb
  config/fedora.yml
  config/redis.yml
  db/schema.rb
  db/seeds.rb
Labels: review

#91 document the default admin password and how to set it
  .env.sample
  README.md
Labels: review
