Repository UCLALibrary/californica, pull requests merged in 2018-10, with the labels that each got.

#254 Remove nightly reingest
  config/schedule.rb
Labels: review

#261 Easily ingest sample data
  lib/tasks/ingest.rake
Labels: review

#260 Fix location facet
  app/controllers/catalog_controller.rb
  app/models/work.rb
Labels: metadata, review

#257 Remove depositor field from search results
  app/controllers/catalog_controller.rb
Labels: review

#262 Update README with UTF-8 information
  README.md
Labels: in progress

#289 Rubocop style fixes
  app/controllers/catalog_controller.rb
  app/renderers/hyrax/renderers/rights_statement_attribute_renderer.rb
  spec/features/import_and_show_work_spec.rb
Labels: in progress
